version: "3.0"

volumes:
  db-data:
    external: false

services:

  db:
    # Pinning MariaDB to point release 10.4.30 works around the issues with the
    # database migrations seen with 10.4.31 in issue #1212.
    #
    # TODO: Get database migrations to work with the latest point releases of
    # MariaDB 10.4.
    image: mariadb:10.4.30
    expose:
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme
    networks:
      - steve
  app:
    build: .
    links:
      - "db:mariadb"
    volumes:
      - .:/code
    expose:
      - "8180"
      - "8443"
    depends_on:
      - db
    networks:
      - steve

  nginx:
    image: nginx:1.19.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - steve
networks:
  steve:
    driver: bridge
